/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppe3.ventes_perpi_co;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author A.A
 */
public class Statistiques extends javax.swing.JPanel {

    /**
     * Creates new form Statistiques
     */
    public Statistiques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTotalProduitVendu = new javax.swing.JLabel();
        jButtonActualiserMontant = new javax.swing.JButton();
        jLabelMontantProduitVendu = new javax.swing.JLabel();

        jLabelTotalProduitVendu.setText("Nombre total de produit vendu :");

        jButtonActualiserMontant.setText("Actualiser le nombre total de produit vendu");
        jButtonActualiserMontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualiserMontantActionPerformed(evt);
            }
        });

        jLabelMontantProduitVendu.setText("Montant total des produits vendus :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMontantProduitVendu)
                    .addComponent(jButtonActualiserMontant)
                    .addComponent(jLabelTotalProduitVendu))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonActualiserMontant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotalProduitVendu)
                .addGap(18, 18, 18)
                .addComponent(jLabelMontantProduitVendu)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualiserMontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualiserMontantActionPerformed
        // Bouton pour actualiser le nombre de ventes total
        this.actualiserMontant();
    }//GEN-LAST:event_jButtonActualiserMontantActionPerformed

    /**
     * Méthode servant à afficher le nombre des produits vendus
     */
    public void actualiserMontant() {

        try {
            ResultSet totalProduitVendu = DAO.getInstance().requeteSelection("SELECT SUM(qte) FROM contenir");
            totalProduitVendu.next();
            jLabelTotalProduitVendu.setText("Nombre total de produit vendu : " + totalProduitVendu.getString(1));
            ResultSet montantProduitVendu = DAO.getInstance().requeteSelection("SELECT SUM(qte*tarif_produit) as montant FROM contenir INNER JOIN produit ON contenir.id_produit = produit.id_produit");
            montantProduitVendu.next();
            jLabelMontantProduitVendu.setText("Montant total des produits vendus : " + montantProduitVendu.getString(1) + "€");
        } catch (SQLException ex) {
            Logger.getLogger(Statistiques.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualiserMontant;
    private javax.swing.JLabel jLabelMontantProduitVendu;
    private javax.swing.JLabel jLabelTotalProduitVendu;
    // End of variables declaration//GEN-END:variables
}
